# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        hostname: lit-harbor-34352.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
        hikari:
            maximumPoolSize: 8
    profiles:
        active: dev
        include: swagger
    mail:
        host: gsmtp.gmail.com
        port: 587
        username: information.elibrary@gmail.com
        password: NyaSaFA0
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: gsmtp.gmail.com

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need to activate TLS (see application-tls.yml)
    cache: # Cache configuration
        ehcache: # Ehcache configuration
            time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
            max-entries: 100 # Number of objects in each cache entry
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count"
        allow-credentials: true
        max-age: 1800
    security:
        authentication:
            jwt:
                # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
                base64-secret: NTMwMTFjNmRhNzk4ODAxZmViNzY0OGE1ZTYwNjBlMDYxMjNhMjkzODM5OGIyNWQ2ZmVkZTg0NDY1YzA5OGVhMDg4NTczNjYzMDJlYjhmMWVjYzk5ZTc4OGFhZTVlNDI2NzRkNzUyN2FhNGJjMjMyZjU5MWIzZmVjZjRiZGFmYmI=
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: treeassist@localhost
        base-url: http://lit-harbor-34352.herokuapp.com
