# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        hostname: lit-harbor-34352.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
        hikari:
            maximumPoolSize: 8
    profiles:
        active: dev
        include:
            - swagger
            # Uncomment to activate TLS for the dev profile
            - tls
    mail:
        host: smtp.gmail.com
        port: 587
        username: information.elibrary@gmail.com
        password: NyaSaFA0
        protocol: smtp
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
jhipster:
    mail:
        from: treeassist@localhost
        base-url: https://lit-harbor-34352.herokuapp.com/#/

